import { existsSync, readdirSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { execAsync } from "@/lib/npm.js";

// JetBrains Marketplace plugin ID for Continue. Matches the bundle ID inside
// the .jar so `<bin> installPlugins` resolves it.
export const CONTINUE_INTELLIJ_PLUGIN_ID =
	"com.github.continuedev.continueintellijextension";

// JetBrains Marketplace plugin ID for Claude Code. This is the `xmlId`
// the marketplace serves (visible at /api/plugins/27310), not the
// brand-derived `com.anthropic.claude-code` you might guess from the URL
// slug — `installPlugins` rejects the slug form as "unknown plugins".
export const CLAUDE_CODE_INTELLIJ_PLUGIN_ID = "com.anthropic.code.plugin";

// Shell launcher names we probe. Limited to PyCharm/IntelliJ IDEA/GoLand for
// now — each batch-mode invocation boots the IDE headless and takes several
// seconds, so we keep the probe list small. Users with other JetBrains IDEs
// (WebStorm, RubyMine, …) fall through to the manual-install hint.
//
// Windows install: the Toolbox "Generate shell scripts" feature writes
// `idea.cmd` / `pycharm.cmd` / `goland.cmd` under whatever directory the
// user picked. Our `execAsync` helper uses `shell: true` on win32 (see
// npm.ts), so the shell resolves the `.cmd` suffix automatically — we
// still spell the launcher without an extension here.
export const JETBRAINS_CLIS = ["idea", "pycharm", "goland"] as const;
type JetBrainsCli = (typeof JETBRAINS_CLIS)[number];

// macOS app-bundle name prefixes per launcher. The launcher script (when
// present on PATH) is generated by Toolbox or hand-rolled; the underlying
// binary always lives at `<Bundle>.app/Contents/MacOS/<cli>`. We match on
// prefix so edition variants ("PyCharm CE.app", "IntelliJ IDEA Ultimate.app")
// are picked up without enumerating every release name.
const MAC_APP_PREFIXES: Record<JetBrainsCli, readonly string[]> = {
	idea: ["IntelliJ IDEA"],
	pycharm: ["PyCharm"],
	goland: ["GoLand"],
};

// Standard macOS install roots. /Applications is the system-wide installer
// target; ~/Applications is where JetBrains Toolbox installs by default.
function macAppSearchRoots(): string[] {
	return ["/Applications", join(homedir(), "Applications")];
}

// Resolve a JetBrains launcher name to a binary inside a macOS `.app` bundle
// when nothing matches on `$PATH`. Returns null when no candidate bundle has
// the expected `Contents/MacOS/<cli>` binary. Only meaningful on darwin.
function findMacAppBinary(cli: JetBrainsCli): string | null {
	if (process.platform !== "darwin") return null;
	const prefixes = MAC_APP_PREFIXES[cli];
	for (const root of macAppSearchRoots()) {
		let entries: string[];
		try {
			entries = readdirSync(root);
		} catch {
			continue;
		}
		for (const entry of entries) {
			if (!entry.endsWith(".app")) continue;
			const stem = entry.slice(0, -".app".length);
			const matched = prefixes.some(
				(p) => stem === p || stem.startsWith(`${p} `),
			);
			if (!matched) continue;
			const bin = join(root, entry, "Contents", "MacOS", cli);
			if (existsSync(bin)) return bin;
		}
	}
	return null;
}

// Soft-fail outcome — matches vscode.ts's InstallExtensionResult. `null`
// means at least one IDE accepted the install and no other IDE we tried
// returned a hard error. `{ warning }` covers two cases: nothing on PATH
// (all-ENOENT), or one or more IDEs ran the command and returned non-zero.
export type InstallPluginResult = null | { warning: string };

// Best-effort install of a JetBrains plugin. Runs `<bin> installPlugins
// <plugin-id>` against every CLI on PATH, sequentially — IDE batch boots
// fight each other if parallelized and the user only needs the plugin in
// IDEs they actually use, so wall time scales with IDEs-on-PATH × ~few
// seconds. ENOENT on a probe is normal ("user doesn't have that IDE");
// on macOS we then look for an installed `.app` bundle whose embedded
// binary handles the same `installPlugins` subcommand, so users who never
// generated Toolbox shell scripts still get the plugin. Non-ENOENT
// failures are aggregated into one warning so the user sees every IDE
// that failed in a single hint.
async function installPlugin(pluginId: string): Promise<InstallPluginResult> {
	let installed = 0;
	const errors: string[] = [];
	for (const cli of JETBRAINS_CLIS) {
		let r = await execAsync(cli, ["installPlugins", pluginId]);
		if (r.error?.code === "ENOENT") {
			const fallback = findMacAppBinary(cli);
			if (fallback) r = await execAsync(fallback, ["installPlugins", pluginId]);
		}
		if (!r.error) {
			installed++;
			continue;
		}
		if (r.error.code === "ENOENT") continue;
		const msg = r.stderr.trim() || r.error.message.trim();
		errors.push(`${cli}: ${msg}`);
	}
	if (errors.length > 0) {
		const prefix =
			installed > 0 ? "installed for some IDEs but failed for others — " : "";
		return { warning: `${prefix}${errors.join("; ")}` };
	}
	if (installed === 0) {
		return {
			warning:
				"JetBrains launcher not found on PATH (PyCharm / IntelliJ IDEA / GoLand)",
		};
	}
	return null;
}

export function installContinuePlugin(): Promise<InstallPluginResult> {
	return installPlugin(CONTINUE_INTELLIJ_PLUGIN_ID);
}

export function installClaudeCodePlugin(): Promise<InstallPluginResult> {
	return installPlugin(CLAUDE_CODE_INTELLIJ_PLUGIN_ID);
}

// Whether at least one of the JetBrains launchers resolves on PATH, or on
// macOS, inside a standard `.app` bundle. Used by `codev update` to decide
// whether to schedule the plugin update — short-circuits on the first
// responder so we don't pay the launcher-probe cost for every IDE when
// one will do.
export async function isAnyJetBrainsCliAvailable(): Promise<boolean> {
	for (const cli of JETBRAINS_CLIS) {
		const r = await execAsync(cli, ["--version"]);
		if (!r.error) return true;
		if (r.error.code === "ENOENT" && findMacAppBinary(cli)) return true;
	}
	return false;
}
