import type { Agent, Session } from "@/providers/types.js";

const HEADER = "<!-- Generated by CoDev -->";

const AGENT_LABEL: Record<Agent, string> = {
	"claude-code": "claude-code",
	codex: "codex",
	opencode: "opencode",
};

export function renderMarkdown(session: Session): string {
	const lines: string[] = [];
	lines.push(HEADER, "");
	lines.push(`# ${formatTitleTimestamp(session.createdAt)}`);
	lines.push("");
	lines.push(
		`<!-- ${AGENT_LABEL[session.agent]} Session ${session.id} (${session.createdAt.toISOString()}) -->`,
	);
	lines.push("");

	let isFirst = true;
	for (const msg of session.messages) {
		if (!isFirst) {
			lines.push("---", "");
		}
		isFirst = false;
		const heading =
			msg.role === "user"
				? "## User"
				: msg.model
					? `## Assistant (${msg.model})`
					: "## Assistant";
		lines.push(heading, "");
		lines.push(msg.content.trimEnd(), "");
	}

	return `${lines.join("\n").trimEnd()}\n`;
}

// Picks a fence longer than any run of backticks in `content`, so user-supplied
// strings (patch bodies, command output, file contents) can't break out of the
// fenced block by containing a literal triple-backtick.
export function codeFence(content: string, lang = ""): string {
	let max = 2;
	const re = /`{3,}/g;
	let m: RegExpExecArray | null = re.exec(content);
	while (m !== null) {
		if (m[0].length > max) max = m[0].length;
		m = re.exec(content);
	}
	const fence = "`".repeat(max + 1);
	return `${fence}${lang}\n${content}\n${fence}`;
}

function formatTitleTimestamp(date: Date): string {
	const pad = (n: number) => String(n).padStart(2, "0");
	return (
		`${date.getUTCFullYear()}-${pad(date.getUTCMonth() + 1)}-${pad(date.getUTCDate())} ` +
		`${pad(date.getUTCHours())}:${pad(date.getUTCMinutes())}:${pad(date.getUTCSeconds())}Z`
	);
}
