import type { Agent, Session } from "@/providers/types.js";

const HEADER = "<!-- Generated by CoDev -->";

const AGENT_LABEL: Record<Agent, string> = {
	"claude-code": "claude-code",
	codex: "codex",
	opencode: "opencode",
};

/**
 * Derive a display title from the first user message when no explicit title is
 * stored by the agent (Claude Code and Codex don't persist session titles).
 * Collapses whitespace, truncates to 80 chars at a word boundary, and appends
 * "…" when cut — mirrors the length OpenCode uses for its AI-generated titles.
 */
export function titleFromFirstMessage(msg: string): string | undefined {
	const clean = msg.replace(/\s+/g, " ").trim();
	if (!clean) return undefined;
	if (clean.length <= 80) return clean;
	const cut = clean.slice(0, 80);
	const lastSpace = cut.lastIndexOf(" ");
	return `${lastSpace > 20 ? cut.slice(0, lastSpace) : cut}…`;
}

export function renderMarkdown(session: Session): string {
	const lines: string[] = [];
	lines.push(HEADER, "");
	const title =
		session.title ||
		(session.firstUserMessage
			? titleFromFirstMessage(session.firstUserMessage)
			: undefined) ||
		formatTitleTimestamp(session.createdAt);
	lines.push(`# ${title}`);
	lines.push("");
	lines.push(
		`<!-- ${AGENT_LABEL[session.agent]} Session ${session.id} (${session.createdAt.toISOString()}) -->`,
	);
	lines.push("");

	let isFirst = true;
	for (const msg of session.messages) {
		if (!isFirst) {
			lines.push("---", "");
		}
		isFirst = false;
		const heading =
			msg.role === "user"
				? "## User"
				: msg.model
					? `## Assistant (${msg.model})`
					: "## Assistant";
		lines.push(heading, "");
		lines.push(msg.content.trimEnd(), "");
	}

	return `${lines.join("\n").trimEnd()}\n`;
}

function formatTitleTimestamp(date: Date): string {
	const pad = (n: number) => String(n).padStart(2, "0");
	return (
		`${date.getUTCFullYear()}-${pad(date.getUTCMonth() + 1)}-${pad(date.getUTCDate())} ` +
		`${pad(date.getUTCHours())}:${pad(date.getUTCMinutes())}:${pad(date.getUTCSeconds())}Z`
	);
}
