import { describe, expect, test } from "bun:test";
import { renderMarkdown } from "@/markdown.js";
import type { Session } from "@/providers/types.js";

function fixture(overrides: Partial<Session> = {}): Session {
	return {
		id: "abc-123",
		agent: "claude-code",
		createdAt: new Date(Date.UTC(2026, 3, 27, 18, 32, 5)),
		firstUserMessage: "Hi",
		messages: [
			{ role: "user", content: "Hi" },
			{ role: "assistant", content: "Hello! How can I help?" },
		],
		...overrides,
	};
}

describe("renderMarkdown", () => {
	test("emits header, title, session comment, and role sections", () => {
		const md = renderMarkdown(fixture());
		expect(md).toContain("<!-- Generated by CoDev -->");
		expect(md).toContain("# 2026-04-27 18:32:05Z");
		expect(md).toContain("<!-- claude-code Session abc-123");
		expect(md).toContain("## User");
		expect(md).toContain("## Assistant");
		expect(md).toContain("Hello! How can I help?");
	});

	test("inserts --- divider when role changes", () => {
		const md = renderMarkdown(
			fixture({
				messages: [
					{ role: "user", content: "Q1" },
					{ role: "assistant", content: "A1" },
					{ role: "user", content: "Q2" },
				],
			}),
		);
		const dividers = md.match(/^---$/gm) ?? [];
		expect(dividers.length).toBe(2);
	});

	test("ends with a single trailing newline", () => {
		const md = renderMarkdown(fixture());
		expect(md.endsWith("\n")).toBe(true);
		expect(md.endsWith("\n\n")).toBe(false);
	});

	test("is deterministic — same session twice produces identical bytes", () => {
		const a = renderMarkdown(fixture());
		const b = renderMarkdown(fixture());
		expect(a).toBe(b);
	});
});
