import { describe, expect, test } from "vitest";
import { renderMarkdown, titleFromFirstMessage } from "@/lib/markdown.js";
import type { Session } from "@/providers/types.js";

function fixture(overrides: Partial<Session> = {}): Session {
	return {
		id: "abc-123",
		agent: "claude-code",
		createdAt: new Date(Date.UTC(2026, 3, 27, 18, 32, 5)),
		firstUserMessage: "Hi",
		messages: [
			{ role: "user", content: "Hi" },
			{ role: "assistant", content: "Hello! How can I help?" },
		],
		...overrides,
	};
}

describe("titleFromFirstMessage", () => {
	test("returns undefined for empty string", () => {
		expect(titleFromFirstMessage("")).toBeUndefined();
		expect(titleFromFirstMessage("   ")).toBeUndefined();
	});

	test("returns the message as-is when short enough", () => {
		expect(titleFromFirstMessage("Fix the login bug")).toBe(
			"Fix the login bug",
		);
	});

	test("collapses internal whitespace", () => {
		expect(titleFromFirstMessage("fix  the\nlogin\n\nbug")).toBe(
			"fix the login bug",
		);
	});

	test("truncates at word boundary with ellipsis when over 80 chars", () => {
		const long =
			"Please implement the new dashboard analytics feature with proper error handling and retry logic";
		// 94 chars — should truncate at word boundary ≤ 80 chars
		const result = titleFromFirstMessage(long);
		if (!result) throw new Error("expected a title");
		expect(result.endsWith("…")).toBe(true);
		expect(result.length).toBeLessThanOrEqual(81); // 80 + "…"
		// Must break at a word boundary (no partial word before ellipsis)
		expect(result.replace(/…$/, "").endsWith(" ")).toBe(false);
		expect(result.replace(/…$/, "").match(/\s$/)).toBeNull();
	});

	test("falls back to hard-cut with ellipsis when no word boundary after 20 chars", () => {
		const noSpace = "a".repeat(100);
		const result = titleFromFirstMessage(noSpace);
		expect(result).toBe(`${"a".repeat(80)}…`);
	});
});

describe("renderMarkdown", () => {
	test("emits header, session comment, and role sections", () => {
		const md = renderMarkdown(fixture());
		expect(md).toContain("<!-- Generated by CoDev -->");
		expect(md).toContain("<!-- claude-code Session abc-123");
		expect(md).toContain("## User");
		expect(md).toContain("## Assistant");
		expect(md).toContain("Hello! How can I help?");
	});

	test("uses explicit session.title when provided (opencode case)", () => {
		const md = renderMarkdown(fixture({ title: "Fix login bug" }));
		expect(md).toContain("# Fix login bug");
		expect(md).not.toContain("# 2026-04-27 18:32:05Z");
	});

	test("derives title from firstUserMessage when no explicit title (claude-code/codex case)", () => {
		const md = renderMarkdown(
			fixture({ title: undefined, firstUserMessage: "Hi" }),
		);
		expect(md).toContain("# Hi");
		expect(md).not.toContain("# 2026-04-27 18:32:05Z");
	});

	test("falls back to timestamp when neither title nor firstUserMessage is set", () => {
		const md = renderMarkdown(
			fixture({ title: undefined, firstUserMessage: undefined }),
		);
		expect(md).toContain("# 2026-04-27 18:32:05Z");
	});

	test("inserts --- divider between every adjacent message", () => {
		const md = renderMarkdown(
			fixture({
				messages: [
					{ role: "user", content: "Q1" },
					{ role: "assistant", content: "A1" },
					{ role: "user", content: "Q2" },
				],
			}),
		);
		const dividers = md.match(/^---$/gm) ?? [];
		expect(dividers.length).toBe(2);
	});

	test("inserts --- divider between same-role neighbors too", () => {
		// New parsers normally consolidate adjacent same-role chunks, but if two
		// neighbors of the same role slip through, the divider still applies.
		const md = renderMarkdown(
			fixture({
				messages: [
					{ role: "user", content: "Q1" },
					{ role: "user", content: "Q2" },
				],
			}),
		);
		const dividers = md.match(/^---$/gm) ?? [];
		expect(dividers.length).toBe(1);
	});

	test("ends with a single trailing newline", () => {
		const md = renderMarkdown(fixture());
		expect(md.endsWith("\n")).toBe(true);
		expect(md.endsWith("\n\n")).toBe(false);
	});

	test("is deterministic — same session twice produces identical bytes", () => {
		const a = renderMarkdown(fixture());
		const b = renderMarkdown(fixture());
		expect(a).toBe(b);
	});

	test("includes model in assistant header when message.model is set", () => {
		const md = renderMarkdown(
			fixture({
				messages: [
					{ role: "user", content: "Hi" },
					{ role: "assistant", content: "Hello!", model: "claude-sonnet-4-6" },
				],
			}),
		);
		expect(md).toContain("## Assistant (claude-sonnet-4-6)");
		expect(md).not.toContain("## Assistant\n");
	});

	test("omits model from assistant header when message.model is not set", () => {
		const md = renderMarkdown(fixture());
		expect(md).toContain("## Assistant\n");
		expect(md).not.toContain("## Assistant (");
	});
});
