import type { Agent, Session } from "@/providers/types.js";

const HEADER = "<!-- Generated by CoDev -->";

const AGENT_LABEL: Record<Agent, string> = {
	"claude-code": "claude-code",
	codex: "codex",
	opencode: "opencode",
};

export function renderMarkdown(session: Session): string {
	const lines: string[] = [];
	lines.push(HEADER, "");
	lines.push(`# ${formatTitleTimestamp(session.createdAt)}`);
	lines.push("");
	lines.push(
		`<!-- ${AGENT_LABEL[session.agent]} Session ${session.id} (${session.createdAt.toISOString()}) -->`,
	);
	lines.push("");

	let prevRole: string | null = null;
	for (const msg of session.messages) {
		if (prevRole && prevRole !== msg.role) {
			lines.push("---", "");
		}
		lines.push(`## ${msg.role === "user" ? "User" : "Assistant"}`, "");
		lines.push(msg.content.trimEnd(), "");
		prevRole = msg.role;
	}

	return `${lines.join("\n").trimEnd()}\n`;
}

function formatTitleTimestamp(date: Date): string {
	const pad = (n: number) => String(n).padStart(2, "0");
	return (
		`${date.getUTCFullYear()}-${pad(date.getUTCMonth() + 1)}-${pad(date.getUTCDate())} ` +
		`${pad(date.getUTCHours())}:${pad(date.getUTCMinutes())}:${pad(date.getUTCSeconds())}Z`
	);
}
